// Generated by CoffeeScript 1.8.0
(function() {
  var load, xobj;

  xobj = new XMLHttpRequest();

  xobj.open("GET", 'graph.json', true);

  xobj.setRequestHeader("Content-type", "application/json");

  xobj.onreadystatechange = function() {
    var json;
    if (xobj.readyState === 4 && xobj.status === 200) {
      json = JSON.parse(xobj.responseText);
      return load(json);
    }
  };

  xobj.send();

  load = function(json) {
    var graph, list;
    graph = new JsonGraph(json);
    graph.asMatrix("weight");
    list = graph.getNodes();
    console.log(graph.getProperties(list[0]));
    return console.log(graph.getProperty(list[0], 'x'));
  };

}).call(this);
